// User Avatar

export enum UserAvatarImageSize {
    "48x48" = "48x49",
    "50x50" = "50x50",
    "60x60" = "60x60",
    "75x75" = "75x75",
    "100x100" = "100x100",
    "110x110" = "110x110",
    "150x150" = "150x150",
    "180x180" = "180x180",
    "352x352" = "352x352",
    "420x420" = "420x420",
    "720x720" = "720x720",
}

export enum UserAvatarImageFormat {
    Png = "Png",
    Jpeg = "Jpeg",
    Webp = "Webp",
}

// User Avatar Bust

export enum UserAvatarBustImageSize {
    "48x48" = "48x49",
    "50x50" = "50x50",
    "60x60" = "60x60",
    "75x75" = "75x75",
    "100x100" = "100x100",
    "150x150" = "150x150",
    "180x180" = "180x180",
    "352x352" = "352x352",
    "420x420" = "420x420",
}

export enum UserAvatarBustImageFormat {
    Png = "Png",
    Webp = "Webp",
}

// User Avatar Headshot

export enum UserAvatarHeadshotImageSize {
    "48x48" = "48x49",
    "50x50" = "50x50",
    "60x60" = "60x60",
    "75x75" = "75x75",
    "100x100" = "100x100",
    "110x110" = "110x110",
    "150x150" = "150x150",
    "180x180" = "180x180",
    "352x352" = "352x352",
    "420x420" = "420x420",
    "720x720" = "720x720",
}

export enum UserAvatarHeadshotImageFormat {
    Png = "Png",
    Jpeg = "Jpeg",
    Webp = "Webp",
}

// Badge Icon

export enum BadgeIconImageSize {
    "150x150" = "150x150",
}

export enum BadgeIconImageFormat {
    Png = "Png",
    Webp = "Webp",
}

// Group Icon

export enum GroupIconImageSize {
    "150x150" = "150x150",
    "420x420" = "420x420",
}

export enum GroupIconImageFormat {
    Png = "Png",
    Webp = "Webp",
}

// Universe Icon

export enum UniverseIconImageReutrnPolicy {
    PlaceHolder = "PlaceHolder",
    ForcePlaceHolder = "ForcePlaceHolder",
    AutoGenerated = "AutoGenerated",
    ForceAutoGenerated = "ForceAutoGenerated",
}

export enum UniverseIconImageSize {
    "50x50" = "50x50",
    "128x128" = "128x128",
    "150x150" = "150x150",
    "256x256" = "256x256",
    "420x420" = "420x420",
    "512x512" = "512x512",
}

export enum UniverseIconImageFormat {
    Png = "Png",
    Jpeg = "Jpeg",
    Webp = "Webp",
}

// Universe Thumbnail

export enum UniverseThumbnailImageSize {
    "768x432" = "768x432",
    "576x324" = "576x324",
    "480x270" = "480x270",
    "384x216" = "256x144",
}

export enum UniverseThumbnailImageFormat {
    Png = "Png",
    Webp = "Webp",
}

// Universe Pass

export enum UniversePassImageSize {
    "150x150" = "150x150",
}

export enum UniversePassImageFormat {
    Png = "Png",
    Webp = "Webp",
}
